# Generated by Django 4.2.11 on 2024-04-14 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='productImage/')),
                ('price', models.PositiveIntegerField()),
                ('discount_price', models.PositiveIntegerField(blank=True, null=True)),
                ('price_range', models.CharField(blank=True, max_length=30, null=True)),
                ('description', models.TextField(blank=True, max_length=100, null=True)),
                ('stock', models.IntegerField(blank=True, null=True)),
                ('brand', models.CharField(blank=True, max_length=30, null=True)),
                ('catagory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eapp.catagory')),
            ],
        ),
    ]
