# Generated by Django 4.2.11 on 2024-04-18 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0003_cart_product_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='ordered_data',
        ),
    ]
