# Generated by Django 4.2.11 on 2024-04-23 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0005_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ordered_data',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
